org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
minecraft_version=1.21
mod_version = 6.0.0
maven_group = de.macbrayne.forge
mod_id = inventorypause

neoforge_version = 21.0.167

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28