plugins {
    id 'multiloader-loader'
    id 'net.neoforged.gradle.userdev' version '7.0.133'
}

// Automatically enable neoforge AccessTransformers if the file exists
// This location is hardcoded in FML and can not be changed.
// https://github.com/neoforged/FancyModLoader/blob/a952595eaaddd571fbc53f43847680b00894e0c1/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java#L118
def at = file('src/main/resources/META-INF/accesstransformer.cfg')
if (at.exists()) {
    minecraft.accessTransformers.file at
}
runs {
    client {
        dependencies {
            runtime('com.moandjiezana.toml:toml4j:0.7.2') {
                transitive(false)
            }
        }

        modSource project.sourceSets.main
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"

    // Mod Dependencies
    implementation('com.moandjiezana.toml:toml4j:0.7.2') {
        transitive(false)
    }
    jarJar('com.moandjiezana.toml:toml4j:[0.7.2]') {
        transitive(false)
    }
}